### ISSUE TITLE
Storage page table not updating after pulling an item

### ISSUE THREAD

**Issue by AshenCat** [jacildoaldrin/tpc_inventory_frontend#14]
### Steps to reproduce

1. >go to storage page
2. >select a storage with only one item
3. >select the item
4. >pull all
5. >(upon successful pull) press back button chevron
6. >storage page still has the storage with the un-updated quantity

### Workarounds to update the page

- use the navigation bar or drawer to change the route then go back

**Comment by jacildoaldrin** [comment]
ill try to figure this one out, but while doing some research, I believe that all we need to do is fetch the data again after form submission.

**Comment by lilianyangc** [comment]
> ill try to figure this one out, but while doing some research, I believe that all we need to do is fetch the data again after form submission.

That's what I know as well.

**Comment by victafrancis** [comment]
Yes

**Comment by AshenCat** [comment]
Solved by the commits in this branch
